import { Platform, StyleSheet } from 'react-native';

import { colors } from './theme';

export const markdownStyles = StyleSheet.create({
  body: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  heading1: {
    color: colors.text,
    fontSize: 25,
    lineHeight: 32,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginTop: 8,
    marginBottom: 14,
  },
  heading2: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '800',
    letterSpacing: -0.25,
    marginTop: 18,
    marginBottom: 10,
  },
  heading3: {
    color: colors.text,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '800',
    marginTop: 15,
    marginBottom: 8,
  },
  heading4: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '800',
    marginTop: 12,
    marginBottom: 6,
  },
  heading5: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
    marginTop: 10,
    marginBottom: 5,
  },
  heading6: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 9,
    marginBottom: 5,
  },
  paragraph: { marginTop: 0, marginBottom: 12 },
  strong: { color: colors.text, fontWeight: '800' },
  em: { color: '#d7d0dc', fontStyle: 'italic' },
  link: { color: colors.primary, textDecorationLine: 'underline' },
  blockquote: {
    marginVertical: 10,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.primaryStrong,
    borderRadius: 8,
    backgroundColor: colors.primaryMuted,
  },
  bullet_list: { marginBottom: 10 },
  ordered_list: { marginBottom: 10 },
  list_item: { marginBottom: 5 },
  bullet_list_icon: { color: colors.primary, marginRight: 8 },
  ordered_list_icon: { color: colors.primary, marginRight: 8 },
  code_inline: {
    color: '#e0d8ff',
    backgroundColor: colors.surface,
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
  },
  code_block: {
    color: '#ded9e2',
    backgroundColor: '#111014',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: 10,
    padding: 12,
    marginVertical: 10,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },
  fence: {
    color: '#ded9e2',
    backgroundColor: '#111014',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: 10,
    padding: 12,
    marginVertical: 10,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },
  hr: { height: 1, backgroundColor: colors.border, marginVertical: 18 },
  table: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginVertical: 10,
  },
  thead: { backgroundColor: colors.surface },
  th: {
    color: colors.text,
    fontWeight: '800',
    padding: 8,
    borderColor: colors.border,
  },
  tr: { borderBottomWidth: 1, borderColor: colors.borderSoft },
  td: { color: colors.textMuted, padding: 8, borderColor: colors.borderSoft },
});

export const conversationMarkdownStyles = StyleSheet.create({
  ...markdownStyles,
  body: {
    ...markdownStyles.body,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  paragraph: { marginTop: 0, marginBottom: 10 },
});

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.background },
  shell: { flex: 1, flexDirection: 'row' },
  shellCompact: { flexDirection: 'column' },
  sidebar: {
    width: 330,
    backgroundColor: colors.sidebar,
    borderRightWidth: 1,
    borderRightColor: colors.borderSoft,
  },
  sidebarCompact: { width: '100%', flex: 1, borderRightWidth: 0 },
  brandRow: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'web' ? 20 : 14,
    paddingBottom: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandIdentity: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  mark: {
    width: 38,
    height: 38,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#f7f5ef',
    borderWidth: 1,
    borderColor: '#e9e5dc',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 4,
    elevation: 3,
  },
  markCompact: { width: 52, height: 52, borderRadius: 16 },
  markImage: { width: '100%', height: '100%' },
  brandName: { color: colors.text, fontWeight: '800', fontSize: 18, letterSpacing: -0.4 },
  brandCaption: { color: colors.textDim, fontSize: 11, marginTop: 1 },
  iconButton: {
    width: 35,
    height: 35,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  projectModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(7, 6, 9, 0.72)',
  },
  projectModalSheet: {
    maxHeight: '86%',
    minHeight: '55%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: colors.border,
    backgroundColor: colors.sidebar,
    overflow: 'hidden',
  },
  projectModalHandle: {
    width: 42,
    height: 5,
    marginTop: 9,
    marginBottom: 4,
    borderRadius: 3,
    backgroundColor: colors.border,
    alignSelf: 'center',
  },
  projectModalHeader: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  projectModalHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  projectModalTitle: { color: colors.text, fontSize: 20, fontWeight: '900' },
  projectModalSubtitle: { color: colors.textDim, fontSize: 11, marginTop: 3 },
  projectAddButton: {
    minHeight: 35,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  projectAddButtonText: { color: colors.primary, fontSize: 11, fontWeight: '800' },
  projectAddPanel: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    backgroundColor: colors.card,
  },
  projectAddLabel: { color: colors.text, fontSize: 12, fontWeight: '800' },
  projectAddHelp: { color: colors.textDim, fontSize: 10, lineHeight: 15, marginTop: 3 },
  projectAddRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  projectAddInput: {
    flex: 1,
    height: 42,
    borderRadius: 11,
    paddingHorizontal: 12,
    color: colors.text,
    fontSize: 12,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  projectAddSubmit: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  projectMutationError: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#6a393b',
    backgroundColor: colors.redMuted,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
  },
  projectMutationErrorText: { flex: 1, color: colors.red, fontSize: 10, lineHeight: 15 },
  projectModalList: { padding: 10, paddingBottom: 24 },
  projectModalRow: {
    minHeight: 72,
    marginBottom: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  projectModalRowSelected: {
    backgroundColor: colors.cardElevated,
    borderColor: '#5c5480',
  },
  projectModalSelect: {
    flex: 1,
    minWidth: 0,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  projectRemoveButton: {
    width: 42,
    height: 42,
    marginRight: 6,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectModalIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  projectModalIconSelected: {
    backgroundColor: colors.primaryMuted,
    borderColor: '#655d8c',
  },
  projectModalCopy: { flex: 1, minWidth: 0 },
  projectModalName: { color: colors.text, fontSize: 14, fontWeight: '700' },
  projectModalNameSelected: { color: colors.primary },
  projectModalPath: { color: colors.textDim, fontSize: 10, lineHeight: 14, marginTop: 4 },
  mobileProjectPicker: {
    minHeight: 78,
    marginHorizontal: 14,
    marginBottom: 4,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#514a6e',
    backgroundColor: colors.primaryMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mobileProjectCopy: { flex: 1, minWidth: 0 },
  mobileProjectEyebrow: {
    color: colors.textDim,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  mobileProjectName: { color: colors.primary, fontSize: 15, fontWeight: '800', marginTop: 2 },
  mobileProjectCount: { color: colors.textMuted, fontSize: 10, marginTop: 3 },
  mobileProjectChevron: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(19, 18, 22, 0.34)',
  },
  projectStrip: { flexGrow: 0, maxHeight: 44 },
  projectStripContent: { paddingHorizontal: 18, paddingVertical: 5, gap: 7 },
  projectChip: {
    height: 31,
    maxWidth: 160,
    paddingHorizontal: 12,
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  projectChipSelected: {
    backgroundColor: colors.primaryMuted,
    borderColor: '#655d8c',
  },
  projectManageChip: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  projectChipText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  projectChipTextSelected: { color: colors.primary },
  searchBox: {
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 15,
    height: 39,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  searchInput: { flex: 1, color: colors.text, fontSize: 14, marginLeft: 8, outlineStyle: 'none' } as never,
  listHeading: {
    paddingHorizontal: 20,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  listHeadingText: {
    color: colors.textMuted,
    fontSize: 11,
    textTransform: 'uppercase',
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  countBadge: {
    minWidth: 20,
    height: 18,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: colors.surface,
  },
  countText: { color: colors.textDim, fontWeight: '700', fontSize: 10 },
  taskList: { flex: 1 },
  taskListContent: { paddingHorizontal: 10, paddingBottom: 16 },
  taskListContentEmpty: { flexGrow: 1, justifyContent: 'center' },
  listLoading: { alignItems: 'center', justifyContent: 'center', padding: 32, gap: 10 },
  listLoadingText: { color: colors.textMuted, fontSize: 11 },
  taskRow: {
    marginBottom: 5,
    padding: 11,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  taskRowSelected: {
    backgroundColor: colors.cardElevated,
    borderColor: colors.border,
  },
  taskRowTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  agentGlyph: {
    width: 31,
    height: 31,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  agentGlyphSelected: { backgroundColor: colors.primaryMuted, borderColor: '#5c5480' },
  taskRowCopy: { flex: 1, minWidth: 0 },
  taskTitle: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 1 },
  taskGoal: { color: colors.textDim, fontSize: 11, lineHeight: 16, marginTop: 3 },
  taskMeta: {
    marginTop: 9,
    paddingLeft: 41,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  taskMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  taskMetaModel: { flex: 1, textAlign: 'right' },
  miniDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.textDim },
  miniDotLive: { backgroundColor: colors.green },
  taskMetaText: { color: colors.textDim, fontSize: 10 },
  gatewayCard: {
    margin: 12,
    borderRadius: 13,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  gatewaySummary: {
    minHeight: 54,
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  gatewaySummaryCopy: { flex: 1, minWidth: 0 },
  gatewayTitle: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  gatewayDot: { width: 7, height: 7, borderRadius: 4 },
  gatewayDotOnline: { backgroundColor: colors.green },
  gatewayDotError: { backgroundColor: colors.red },
  gatewayLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  gatewayUrl: { color: colors.textDim, fontSize: 9, marginTop: 4, fontFamily: 'monospace' },
  gatewayEditor: {
    padding: 10,
    paddingTop: 0,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  gatewayInput: {
    color: colors.text,
    fontSize: 11,
    paddingHorizontal: 9,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    marginTop: 10,
  },
  gatewayActions: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  gatewayConnect: { paddingHorizontal: 4, paddingVertical: 3 },
  gatewayConnectText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  gatewayReset: { paddingHorizontal: 4, paddingVertical: 3 },
  gatewayResetText: { color: colors.textDim, fontSize: 10, fontWeight: '700' },
  taskPane: { flex: 1, backgroundColor: colors.background },
  taskHeader: {
    minHeight: 76,
    paddingHorizontal: 22,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  taskHeaderCompact: {
    minHeight: 0,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  taskHeaderLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 11, minWidth: 0 },
  taskHeaderLeftCompact: { flex: 1, width: 'auto', gap: 8 },
  taskHeroIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.primaryMuted,
    borderWidth: 1,
    borderColor: '#5b537d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskHeaderCopy: { flex: 1, minWidth: 0 },
  taskTitleLine: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  taskHeroTitle: { color: colors.text, fontSize: 16, fontWeight: '800', flexShrink: 1 },
  taskHeroGoal: { color: colors.textDim, fontSize: 11, marginTop: 4 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  headerActionsCompact: { flexShrink: 0, justifyContent: 'flex-end', gap: 5 },
  actionButton: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardElevated,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  actionButtonCompact: { minHeight: 35, paddingHorizontal: 10, borderRadius: 10 },
  actionButtonIconOnly: { width: 35, paddingHorizontal: 0 },
  actionButtonPrimary: { backgroundColor: colors.primary, borderColor: colors.primary },
  actionButtonDanger: { backgroundColor: colors.redMuted, borderColor: '#6a393b' },
  actionButtonText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  actionButtonTextPrimary: { color: '#211a4a' },
  actionButtonTextDanger: { color: colors.red },
  pressed: { opacity: 0.72 },
  disabled: { opacity: 0.45 },
  statusPill: {
    height: 24,
    paddingHorizontal: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
  },
  statusRunning: { backgroundColor: colors.greenMuted, borderColor: '#315a40' },
  statusIdle: { backgroundColor: colors.surface, borderColor: colors.border },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  dotRunning: { backgroundColor: colors.green },
  dotIdle: { backgroundColor: colors.textDim },
  statusText: { color: colors.textMuted, fontSize: 10, fontWeight: '700' },
  statusTextRunning: { color: colors.green },
  tabs: {
    height: 48,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  tab: {
    height: 42,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabSelected: { borderBottomColor: colors.primary },
  tabText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  tabTextSelected: { color: colors.primary },
  conversationContent: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    backgroundColor: colors.background,
  },
  conversation: { flex: 1, minHeight: 0, position: 'relative' },
  conversationList: { flex: 1 },
  conversationListContent: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
  },
  conversationListContentEmpty: { flexGrow: 1, justifyContent: 'center' },
  conversationUserRow: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 16,
    paddingLeft: 44,
  },
  conversationUserBubble: {
    maxWidth: '92%',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    borderBottomRightRadius: 5,
    backgroundColor: colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 2,
  },
  conversationUserText: {
    color: '#211a4a',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
  },
  conversationUserDelivery: {
    color: 'rgba(33, 26, 74, 0.62)',
    fontSize: 9,
    fontWeight: '800',
    textAlign: 'right',
    marginTop: 5,
  },
  conversationAgentRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingRight: 18,
    marginBottom: 17,
  },
  conversationAgentAvatar: {
    width: 28,
    height: 28,
    marginTop: 1,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: '#f7f5ef',
    borderWidth: 1,
    borderColor: '#e9e5dc',
  },
  conversationAgentAvatarImage: { width: '100%', height: '100%' },
  conversationAgentBody: {
    flex: 1,
    minWidth: 0,
    paddingTop: 1,
  },
  conversationTool: {
    marginLeft: 38,
    marginBottom: 11,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  conversationToolHeader: {
    minHeight: 62,
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  conversationToolIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryMuted,
    borderWidth: 1,
    borderColor: '#5b537d',
  },
  conversationToolCopy: { flex: 1, minWidth: 0 },
  conversationToolTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  conversationToolName: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  conversationToolStatus: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  conversationToolStatusText: { fontSize: 9, fontWeight: '800' },
  conversationToolSummary: {
    color: colors.textDim,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
  },
  conversationToolDetails: {
    paddingHorizontal: 11,
    paddingBottom: 11,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    backgroundColor: '#17161a',
  },
  conversationToolSection: { marginTop: 10 },
  conversationToolSectionLabel: {
    color: colors.textDim,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  conversationToolCode: {
    color: '#dcd7e0',
    fontSize: 10,
    lineHeight: 15,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  conversationQuestion: {
    marginLeft: 38,
    marginBottom: 15,
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#24222b',
    borderWidth: 1,
    borderColor: '#615987',
  },
  conversationQuestionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 12,
  },
  conversationQuestionIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryMuted,
  },
  conversationQuestionHeaderCopy: { flex: 1, minWidth: 0 },
  conversationQuestionTitle: { color: colors.text, fontSize: 13, fontWeight: '900' },
  conversationQuestionStatus: { color: colors.primary, fontSize: 9, fontWeight: '700', marginTop: 2 },
  conversationPrompt: { marginTop: 3, marginBottom: 11 },
  conversationPromptHeader: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  conversationPromptText: { color: colors.text, fontSize: 13, lineHeight: 19, fontWeight: '700' },
  conversationPromptHint: { color: colors.textDim, fontSize: 9, marginTop: 4 },
  conversationOptions: { gap: 7, marginTop: 10 },
  conversationOption: {
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  conversationOptionSelected: {
    backgroundColor: colors.primaryMuted,
    borderColor: colors.primaryStrong,
  },
  conversationOptionDisabled: { opacity: 0.6 },
  conversationOptionIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#686371',
  },
  conversationOptionIndicatorSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  conversationOptionCopy: { flex: 1, minWidth: 0 },
  conversationOptionLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  conversationOptionLabelSelected: { color: colors.primary },
  conversationOptionDescription: { color: colors.textDim, fontSize: 9, lineHeight: 13, marginTop: 3 },
  conversationCustomAnswer: { marginTop: 2, marginBottom: 11 },
  conversationCustomAnswerLabel: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  conversationCustomAnswerInput: {
    minHeight: 76,
    maxHeight: 150,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 12,
    color: colors.text,
    fontSize: 12,
    lineHeight: 18,
    textAlignVertical: 'top',
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.primaryStrong,
  },
  conversationAnswerButton: {
    minHeight: 38,
    paddingHorizontal: 13,
    borderRadius: 12,
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.primary,
  },
  conversationAnswerButtonDisabled: { opacity: 0.38 },
  conversationAnswerButtonText: { color: '#211a4a', fontSize: 10, fontWeight: '900' },
  conversationAnswerFeedback: {
    color: colors.amber,
    fontSize: 9,
    lineHeight: 14,
    marginTop: 8,
    textAlign: 'right',
  },
  conversationQuestionAnswer: {
    color: colors.textDim,
    fontSize: 10,
    lineHeight: 15,
    paddingTop: 3,
  },
  conversationEvent: { alignItems: 'center', paddingVertical: 8, marginBottom: 8 },
  conversationEventText: { color: colors.textDim, fontSize: 10, fontWeight: '700' },
  conversationLoading: { alignItems: 'center', justifyContent: 'center', gap: 10 },
  conversationLoadingText: { color: colors.textMuted, fontSize: 11 },
  conversationLoadEarlier: {
    minHeight: 34,
    marginBottom: 18,
    alignSelf: 'center',
    paddingHorizontal: 11,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  conversationLoadEarlierText: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  conversationWorking: {
    marginLeft: 38,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  conversationWorkingText: { color: colors.green, fontSize: 10, fontWeight: '700' },
  conversationActivityText: { color: colors.amber, fontSize: 10, fontWeight: '700' },
  conversationLatest: {
    position: 'absolute',
    right: 16,
    bottom: 14,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 5,
  },
  conversationLatestText: { color: '#211a4a', fontSize: 10, fontWeight: '900' },
  activityContent: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: 1120,
    padding: 20,
    alignSelf: 'center',
  },
  activityContentCompact: { padding: 8 },
  activityContentKeyboard: { padding: 0 },
  activityContentFullscreen: { maxWidth: '100%', padding: 0 },
  activityContentHidden: { display: 'none' },
  keyboardFocusOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 20,
    minHeight: 34,
    paddingLeft: 9,
    paddingRight: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(25, 24, 29, 0.94)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  keyboardFocusLabel: { color: colors.textDim, fontSize: 9, fontWeight: '700' },
  keyboardDismissButton: {
    minHeight: 26,
    paddingHorizontal: 7,
    borderRadius: 8,
    backgroundColor: colors.primaryMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  keyboardDismissButtonText: { color: colors.primary, fontSize: 9, fontWeight: '800' },
  mainScroll: { flex: 1 },
  mainContent: {
    padding: 20,
    paddingBottom: 36,
    maxWidth: 1120,
    width: '100%',
    alignSelf: 'center',
  },
  mainContentCompact: { padding: 12, paddingBottom: 28 },
  contentStack: { gap: 12 },
  sectionCard: {
    borderRadius: 16,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  sectionCardFill: { flex: 1, minHeight: 0 },
  sectionHeader: {
    height: 49,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  sectionActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionIconButton: {
    width: 30,
    height: 30,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionMeta: { color: colors.textDim, fontSize: 10, fontWeight: '700' },
  captureLineCount: { color: colors.textDim, fontSize: 9, fontFamily: 'monospace' },
  liveStatus: {
    height: 24,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  liveStatusError: { borderColor: '#6a393b', backgroundColor: colors.redMuted },
  liveStatusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.amber },
  liveStatusDotOnline: { backgroundColor: colors.green },
  liveStatusDotError: { backgroundColor: colors.red },
  liveStatusText: { color: colors.amber, fontSize: 9, fontWeight: '800' },
  liveStatusTextOnline: { color: colors.green },
  liveStatusTextError: { color: colors.red },
  terminalHeader: {
    height: 36,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: '#17161a',
  },
  terminalLights: { flexDirection: 'row', gap: 5 },
  terminalLight: { width: 8, height: 8, borderRadius: 4 },
  terminalTarget: { flex: 1, color: colors.textDim, fontSize: 10, fontFamily: 'monospace' },
  terminal: { minHeight: 260, width: '100%', backgroundColor: '#111014' },
  terminalContent: { padding: 16, alignItems: 'flex-start' },
  liveTerminalShell: {
    width: '100%',
    backgroundColor: '#111014',
    overflow: 'hidden',
  },
  liveTerminalFill: { flex: 1, minHeight: 240 },
  liveTerminalFullscreen: { flex: 1, minHeight: 0 },
  liveTerminalWebView: { flex: 1, backgroundColor: '#111014' },
  liveTerminalGestureLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    backgroundColor: 'transparent',
  },
  liveTerminalControls: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    zIndex: 3,
    padding: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(99, 93, 112, 0.72)',
    backgroundColor: 'rgba(25, 24, 29, 0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  liveTerminalControl: {
    minWidth: 42,
    height: 30,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4a4751',
    backgroundColor: colors.cardElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveTerminalControlActive: {
    borderColor: colors.primaryStrong,
    backgroundColor: colors.primary,
  },
  liveTerminalControlText: { color: colors.textMuted, fontSize: 10, fontWeight: '800' },
  liveTerminalControlTextActive: { color: '#211a4a' },
  liveTerminalError: {
    position: 'absolute',
    left: 9,
    right: 9,
    bottom: 9,
    zIndex: 4,
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#6a393b',
    backgroundColor: 'rgba(72, 42, 43, 0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveTerminalErrorText: { flex: 1, color: colors.red, fontSize: 10, lineHeight: 14 },
  liveTerminalRetry: {
    minHeight: 28,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#815052',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveTerminalRetryText: { color: colors.red, fontSize: 9, fontWeight: '800' },
  fullscreenTerminalHeader: {
    minHeight: 62,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    backgroundColor: colors.sidebar,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  fullscreenTerminalHeaderCopy: { flex: 1, minWidth: 0 },
  fullscreenTerminalTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  fullscreenTerminalTarget: {
    color: colors.textDim,
    fontSize: 9,
    fontFamily: 'monospace',
    marginTop: 3,
  },
  fullscreenTerminalHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fullscreenTerminalKeyboard: {
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    backgroundColor: colors.background,
  },
  terminalKeysToggle: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardElevated,
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  terminalKeysToggleText: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  terminalText: {
    color: '#dcd7e0',
    fontSize: 11,
    lineHeight: 17,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  terminalFoot: {
    minHeight: 36,
    paddingHorizontal: 13,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 6,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  terminalFootCopy: { flex: 1, minWidth: 210, flexDirection: 'row', alignItems: 'center', gap: 6 },
  terminalFootText: { flex: 1, color: colors.textDim, fontSize: 10 },
  terminalFootCompactText: { color: colors.textDim, fontSize: 9, fontWeight: '700' },
  terminalFootActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  loadMoreButton: {
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  loadMoreButtonText: { color: colors.primary, fontSize: 10, fontWeight: '700' },
  fontSizeControl: {
    height: 30,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  fontSizeButton: {
    width: 34,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardElevated,
  },
  fontSizeButtonText: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  fontSizeValue: {
    width: 27,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 9,
    fontFamily: 'monospace',
  },
  emptyState: { alignItems: 'center', paddingHorizontal: 24, paddingVertical: 38 },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryMuted,
    marginBottom: 13,
  },
  emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 14 },
  emptyDetail: {
    color: colors.textDim,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
    textAlign: 'center',
    maxWidth: 320,
  },
  diffList: { padding: 10, gap: 8 },
  inlineError: {
    margin: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6a393b',
    backgroundColor: colors.redMuted,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  inlineErrorCopy: { flex: 1, minWidth: 0 },
  inlineErrorTitle: { color: colors.red, fontSize: 11, fontWeight: '800' },
  inlineErrorText: { color: colors.red, fontSize: 10, lineHeight: 15, marginTop: 3 },
  diffFile: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
    backgroundColor: colors.background,
  },
  diffFileHeader: {
    minHeight: 40,
    paddingHorizontal: 11,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  diffFileName: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7, minWidth: 0 },
  diffPath: { color: colors.text, fontSize: 11, fontWeight: '600', flexShrink: 1 },
  diffStats: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  additions: { color: colors.green, fontSize: 10, fontWeight: '700' },
  deletions: { color: colors.red, fontSize: 10, fontWeight: '700' },
  diffStatus: {
    color: colors.amber,
    backgroundColor: colors.amberMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    fontSize: 9,
    fontWeight: '800',
  },
  patchShell: { borderTopWidth: 1, borderTopColor: colors.borderSoft },
  patch: { backgroundColor: '#111014' },
  patchText: {
    padding: 12,
    color: '#d8d2dc',
    fontSize: 10,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  expandButton: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.card,
  },
  expandButtonText: { color: colors.primary, fontSize: 10, fontWeight: '700' },
  markdownDocument: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 18 },
  markdownModeButton: {
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.cardElevated,
  },
  markdownModeButtonText: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  notesSourceText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 19,
    padding: 18,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  terminalKeyboard: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    marginBottom: 9,
    padding: 9,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  terminalKeyboardHeader: {
    marginBottom: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  terminalKeyboardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  terminalKeyboardTitle: { color: colors.text, fontSize: 10, fontWeight: '800' },
  terminalKeyboardHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  terminalKeyboardStatus: { color: colors.textDim, fontSize: 9, fontFamily: 'monospace' },
  keyboardExpandButton: {
    minHeight: 26,
    paddingHorizontal: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  keyboardExpandButtonText: { color: colors.primary, fontSize: 9, fontWeight: '800' },
  terminalKeyRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  terminalKey: {
    flex: 1,
    minWidth: 0,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4a4751',
    borderBottomWidth: 3,
    backgroundColor: colors.cardElevated,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 2,
    elevation: 3,
  },
  terminalKeyWide: { flex: 1.35 },
  terminalKeyPrimary: {
    borderColor: '#8e82d8',
    backgroundColor: colors.primary,
  },
  terminalKeyDanger: {
    borderColor: '#6a393b',
    backgroundColor: colors.redMuted,
  },
  terminalKeyDisabled: { opacity: 0.34 },
  terminalKeyPressed: {
    transform: [{ translateY: 2 }],
    borderBottomWidth: 1,
    opacity: 0.82,
  },
  terminalKeyText: { color: colors.text, fontSize: 13, fontWeight: '800' },
  terminalKeyTextPrimary: { color: '#211a4a' },
  terminalKeyTextDanger: { color: colors.red },
  terminalKeyboardError: {
    marginTop: 7,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.redMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  terminalKeyboardErrorText: { flex: 1, color: colors.red, fontSize: 9 },
  terminalKeyboardHint: { color: colors.textDim, fontSize: 8, lineHeight: 12, marginTop: 6 },
  expandedKeyboardOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(7, 6, 9, 0.76)',
  },
  expandedKeyboardSheet: {
    maxHeight: '84%',
    minHeight: '62%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: colors.border,
    backgroundColor: colors.sidebar,
    overflow: 'hidden',
  },
  expandedKeyboardHeader: {
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  expandedKeyboardTitle: { color: colors.text, fontSize: 17, fontWeight: '900' },
  expandedKeyboardSubtitle: { color: colors.textDim, fontSize: 10, marginTop: 3 },
  expandedKeyboardContent: { padding: 14, paddingBottom: 30 },
  expandedKeyboardSection: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: 12,
    marginBottom: 7,
  },
  expandedNavigation: { flexDirection: 'row', alignItems: 'stretch', gap: 12 },
  expandedDpad: { flex: 1.1, gap: 5 },
  expandedUtilityKeys: { flex: 1, gap: 5 },
  expandedKeyRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 5 },
  expandedKeySpacer: { flex: 1, height: 38 },
  expandedKeyboardWarning: {
    color: colors.amber,
    fontSize: 9,
    lineHeight: 14,
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#665528',
    backgroundColor: colors.amberMuted,
  },
  composerShell: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'web' ? 16 : 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    backgroundColor: colors.background,
  },
  mobileProjectCountRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  mobileProjectElsewhere: { color: colors.green, fontSize: 11, fontWeight: '700' },
  activityRingHost: { alignItems: 'center', justifyContent: 'center' },
  activityRing: {
    position: 'absolute',
    borderWidth: 2,
    // A gap in the stroke is what reads as motion once the ring spins.
    borderLeftColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  activityRingWorking: { borderRightColor: 'transparent' },
  composerShellCompact: { paddingHorizontal: 10, paddingTop: 6, paddingBottom: 6 },
  composerError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9,
    backgroundColor: colors.redMuted,
    borderWidth: 1,
    borderColor: '#6a393b',
  },
  composerErrorText: { color: colors.red, fontSize: 11, flex: 1 },
  composer: {
    width: '100%',
    maxWidth: 900,
    minHeight: 44,
    maxHeight: 150,
    alignSelf: 'center',
    borderRadius: 16,
    paddingLeft: 6,
    paddingRight: 7,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: colors.cardElevated,
    borderWidth: 1,
    borderColor: colors.border,
  },
  composerOffline: {
    backgroundColor: colors.card,
    borderColor: colors.borderSoft,
    opacity: 0.82,
  },
  composerKeysButton: {
    width: 34,
    height: 34,
    marginRight: 5,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerKeysButtonActive: { backgroundColor: colors.primaryMuted },
  composerAgentMark: {
    width: 30,
    height: 30,
    marginLeft: 2,
    marginRight: 7,
    marginBottom: 2,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: '#f7f5ef',
    borderWidth: 1,
    borderColor: '#e9e5dc',
  },
  composerAgentMarkImage: { width: '100%', height: '100%' },
  composerInput: {
    flex: 1,
    minHeight: 32,
    maxHeight: 130,
    paddingVertical: 7,
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
    outlineStyle: 'none',
  } as never,
  sendButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  sendButtonForce: {
    backgroundColor: colors.amber,
    shadowColor: colors.amber,
    shadowOpacity: 0.28,
    shadowRadius: 7,
  },
  sendButtonDisabled: { backgroundColor: colors.surface, opacity: 0.55 },
  forceSendAction: {
    minHeight: 30,
    marginTop: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: colors.amberMuted,
    borderWidth: 1,
    borderColor: '#665528',
  },
  forceSendHint: {
    color: colors.amber,
    fontSize: 9,
    fontWeight: '800',
    textAlign: 'center',
  },
  forceSendFeedback: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
  },
  composerOfflineHint: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  composerOfflineHintText: {
    color: colors.textDim,
    fontSize: 9,
    fontWeight: '700',
  },
  composerHint: {
    color: colors.textDim,
    fontSize: 9,
    textAlign: 'center',
    marginTop: 6,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.redMuted,
    borderWidth: 1,
    borderColor: '#6a393b',
  },
  errorText: { color: colors.red, fontSize: 11, flex: 1 },
  noSelection: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  noSelectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 18 },
  noSelectionDetail: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 7,
    textAlign: 'center',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: { color: colors.textMuted, marginTop: 11, fontSize: 12 },
  connectScreen: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  connectCard: {
    width: '100%',
    maxWidth: 440,
    alignItems: 'center',
    padding: 28,
    borderRadius: 22,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  connectTitle: { color: colors.text, fontSize: 21, fontWeight: '900', marginTop: 17 },
  connectDetail: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 7,
    marginBottom: 17,
  },
  connectError: {
    width: '100%',
    padding: 10,
    borderRadius: 10,
    backgroundColor: colors.redMuted,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 11,
  },
  connectErrorText: { color: colors.red, fontSize: 11, flex: 1 },
  connectInput: {
    width: '100%',
    height: 43,
    borderRadius: 11,
    paddingHorizontal: 12,
    color: colors.text,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 11,
  },
  connectReset: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  connectResetText: { color: colors.primary, fontSize: 10, fontWeight: '700' },
  connectCommand: {
    color: colors.textDim,
    fontSize: 9,
    fontFamily: 'monospace',
    marginTop: 14,
  },
});
